### PR TITLE
Switch to Hugo

### PR DESCRIPTION
**Pull request by yqlbu**

### CODE REVIEW

**Comment by yqlbu** [comment]
Journey Started! Wanna introduce my teammate @kunish to join the Jetson Community.

**Comment by yqlbu** [comment]
Added `pre-commit` to the repository. To install, simply run `brew install pre-commit`

**Comment by yqlbu** [comment]
Added two new files, `CODEOWNER` and `contribute.md` to the repository.

**Comment by kunish** [comment]
Just added hugo theme [compose](https://github.com/onweru/compose) as a git submodule which lives in `src/themes/compose`.

We may further discuss how to enable and use it.

**Pull request merged**
